# Generated by Django 4.2 on 2023-04-11 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0002_alter_employee_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("visited", models.BooleanField(default=True)),
                ("time_visit_start", models.TimeField()),
                ("time_visit_end", models.TimeField()),
                ("reason", models.CharField(max_length=255)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.employee"
                    ),
                ),
            ],
        ),
    ]
