# Generated by Django 4.2 on 2023-04-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="image/"),
        ),
    ]
